global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
        labels:
          app: "prometheus"

  - job_name: "application"
    static_configs:
      - targets:
          - 172.31.13.218:8080
        labels:
          service: "demo-app"
          metric_type: "application"
          env: "dev"

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - 172.31.13.218:9100
        labels:
          host: "app-ec2"
          metric_type: "system"
          env: "dev"

